# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyMARIS_Converter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 903)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.data_sets_frame = QtWidgets.QFrame(self.centralwidget)
        self.data_sets_frame.setGeometry(QtCore.QRect(70, 10, 641, 161))
        self.data_sets_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.data_sets_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.data_sets_frame.setObjectName("data_sets_frame")
        self.load_magellan_pushButton = QtWidgets.QPushButton(self.data_sets_frame)
        self.load_magellan_pushButton.setGeometry(QtCore.QRect(0, 0, 121, 23))
        self.load_magellan_pushButton.setObjectName("load_magellan_pushButton")
        self.remove_pushButton = QtWidgets.QPushButton(self.data_sets_frame)
        self.remove_pushButton.setGeometry(QtCore.QRect(550, 0, 91, 23))
        self.remove_pushButton.setObjectName("remove_pushButton")
        self.magellan_dataset_listWidget = QtWidgets.QListWidget(self.data_sets_frame)
        self.magellan_dataset_listWidget.setGeometry(QtCore.QRect(0, 30, 641, 131))
        self.magellan_dataset_listWidget.setObjectName("magellan_dataset_listWidget")
        self.subset_frame = QtWidgets.QFrame(self.centralwidget)
        self.subset_frame.setGeometry(QtCore.QRect(70, 180, 641, 251))
        self.subset_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subset_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.subset_frame.setObjectName("subset_frame")
        self.subsample_tabWidget = QtWidgets.QTabWidget(self.subset_frame)
        self.subsample_tabWidget.setGeometry(QtCore.QRect(40, 10, 561, 191))
        self.subsample_tabWidget.setObjectName("subsample_tabWidget")
        self.saving_tab = QtWidgets.QWidget()
        self.saving_tab.setObjectName("saving_tab")
        self.save_directory_lineEdit = QtWidgets.QLineEdit(self.saving_tab)
        self.save_directory_lineEdit.setGeometry(QtCore.QRect(70, 50, 341, 21))
        self.save_directory_lineEdit.setObjectName("save_directory_lineEdit")
        self.browse_pushButton = QtWidgets.QPushButton(self.saving_tab)
        self.browse_pushButton.setGeometry(QtCore.QRect(410, 50, 91, 21))
        self.browse_pushButton.setObjectName("browse_pushButton")
        self.save_name_lineEdit = QtWidgets.QLineEdit(self.saving_tab)
        self.save_name_lineEdit.setGeometry(QtCore.QRect(70, 110, 341, 21))
        self.save_name_lineEdit.setObjectName("save_name_lineEdit")
        self.auto_generate_pushButton = QtWidgets.QPushButton(self.saving_tab)
        self.auto_generate_pushButton.setGeometry(QtCore.QRect(410, 110, 91, 21))
        self.auto_generate_pushButton.setObjectName("auto_generate_pushButton")
        self.save_directory_label = QtWidgets.QLabel(self.saving_tab)
        self.save_directory_label.setGeometry(QtCore.QRect(80, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_directory_label.setFont(font)
        self.save_directory_label.setObjectName("save_directory_label")
        self.save_name_label = QtWidgets.QLabel(self.saving_tab)
        self.save_name_label.setGeometry(QtCore.QRect(80, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_name_label.setFont(font)
        self.save_name_label.setObjectName("save_name_label")
        self.subsample_tabWidget.addTab(self.saving_tab, "")
        self.channel_tab = QtWidgets.QWidget()
        self.channel_tab.setObjectName("channel_tab")
        self.included_listWidget = QtWidgets.QListWidget(self.channel_tab)
        self.included_listWidget.setGeometry(QtCore.QRect(130, 40, 131, 101))
        self.included_listWidget.setObjectName("included_listWidget")
        self.excluded_listWidget = QtWidgets.QListWidget(self.channel_tab)
        self.excluded_listWidget.setGeometry(QtCore.QRect(280, 40, 131, 101))
        self.excluded_listWidget.setObjectName("excluded_listWidget")
        self.included_channels_label = QtWidgets.QLabel(self.channel_tab)
        self.included_channels_label.setGeometry(QtCore.QRect(140, 20, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.included_channels_label.setFont(font)
        self.included_channels_label.setObjectName("included_channels_label")
        self.excluded_channels_label = QtWidgets.QLabel(self.channel_tab)
        self.excluded_channels_label.setGeometry(QtCore.QRect(290, 20, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.excluded_channels_label.setFont(font)
        self.excluded_channels_label.setObjectName("excluded_channels_label")
        self.remove_channels_pushButton = QtWidgets.QPushButton(self.channel_tab)
        self.remove_channels_pushButton.setGeometry(QtCore.QRect(160, 140, 75, 23))
        self.remove_channels_pushButton.setObjectName("remove_channels_pushButton")
        self.add_channels_pushButton = QtWidgets.QPushButton(self.channel_tab)
        self.add_channels_pushButton.setGeometry(QtCore.QRect(310, 140, 75, 23))
        self.add_channels_pushButton.setObjectName("add_channels_pushButton")
        self.subsample_tabWidget.addTab(self.channel_tab, "")
        self.space_tab = QtWidgets.QWidget()
        self.space_tab.setObjectName("space_tab")
        self.x_min_lineEdit = QtWidgets.QLineEdit(self.space_tab)
        self.x_min_lineEdit.setGeometry(QtCore.QRect(20, 60, 71, 20))
        self.x_min_lineEdit.setObjectName("x_min_lineEdit")
        self.x_max_lineEdit = QtWidgets.QLineEdit(self.space_tab)
        self.x_max_lineEdit.setGeometry(QtCore.QRect(100, 60, 71, 20))
        self.x_max_lineEdit.setObjectName("x_max_lineEdit")
        self.y_min_lineEdit = QtWidgets.QLineEdit(self.space_tab)
        self.y_min_lineEdit.setGeometry(QtCore.QRect(200, 60, 71, 20))
        self.y_min_lineEdit.setObjectName("y_min_lineEdit")
        self.y_max_lineEdit = QtWidgets.QLineEdit(self.space_tab)
        self.y_max_lineEdit.setGeometry(QtCore.QRect(280, 60, 71, 20))
        self.y_max_lineEdit.setObjectName("y_max_lineEdit")
        self.z_min_lineEdit = QtWidgets.QLineEdit(self.space_tab)
        self.z_min_lineEdit.setGeometry(QtCore.QRect(380, 60, 71, 20))
        self.z_min_lineEdit.setObjectName("z_min_lineEdit")
        self.z_max_lineEdit = QtWidgets.QLineEdit(self.space_tab)
        self.z_max_lineEdit.setGeometry(QtCore.QRect(460, 60, 71, 20))
        self.z_max_lineEdit.setObjectName("z_max_lineEdit")
        self.x_min_label = QtWidgets.QLabel(self.space_tab)
        self.x_min_label.setGeometry(QtCore.QRect(30, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x_min_label.setFont(font)
        self.x_min_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_min_label.setObjectName("x_min_label")
        self.x_max_label = QtWidgets.QLabel(self.space_tab)
        self.x_max_label.setGeometry(QtCore.QRect(110, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.x_max_label.setFont(font)
        self.x_max_label.setAlignment(QtCore.Qt.AlignCenter)
        self.x_max_label.setObjectName("x_max_label")
        self.y_min_label = QtWidgets.QLabel(self.space_tab)
        self.y_min_label.setGeometry(QtCore.QRect(210, 40, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.y_min_label.setFont(font)
        self.y_min_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_min_label.setObjectName("y_min_label")
        self.y_max_label = QtWidgets.QLabel(self.space_tab)
        self.y_max_label.setGeometry(QtCore.QRect(290, 40, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.y_max_label.setFont(font)
        self.y_max_label.setAlignment(QtCore.Qt.AlignCenter)
        self.y_max_label.setObjectName("y_max_label")
        self.z_min_label = QtWidgets.QLabel(self.space_tab)
        self.z_min_label.setGeometry(QtCore.QRect(390, 40, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.z_min_label.setFont(font)
        self.z_min_label.setAlignment(QtCore.Qt.AlignCenter)
        self.z_min_label.setObjectName("z_min_label")
        self.z_max_label = QtWidgets.QLabel(self.space_tab)
        self.z_max_label.setGeometry(QtCore.QRect(470, 40, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.z_max_label.setFont(font)
        self.z_max_label.setAlignment(QtCore.Qt.AlignCenter)
        self.z_max_label.setObjectName("z_max_label")
        self.reset_space_pushButton = QtWidgets.QPushButton(self.space_tab)
        self.reset_space_pushButton.setGeometry(QtCore.QRect(240, 100, 75, 23))
        self.reset_space_pushButton.setObjectName("reset_space_pushButton")
        self.subsample_tabWidget.addTab(self.space_tab, "")
        self.time_tab = QtWidgets.QWidget()
        self.time_tab.setObjectName("time_tab")
        self.first_frame_spinBox = QtWidgets.QSpinBox(self.time_tab)
        self.first_frame_spinBox.setGeometry(QtCore.QRect(190, 60, 42, 22))
        self.first_frame_spinBox.setObjectName("first_frame_spinBox")
        self.final_frame_spinBox = QtWidgets.QSpinBox(self.time_tab)
        self.final_frame_spinBox.setGeometry(QtCore.QRect(320, 60, 42, 22))
        self.final_frame_spinBox.setObjectName("final_frame_spinBox")
        self.first_frame_label = QtWidgets.QLabel(self.time_tab)
        self.first_frame_label.setGeometry(QtCore.QRect(170, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.first_frame_label.setFont(font)
        self.first_frame_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_frame_label.setObjectName("first_frame_label")
        self.label_3 = QtWidgets.QLabel(self.time_tab)
        self.label_3.setGeometry(QtCore.QRect(300, 40, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.reset_time_pushButton = QtWidgets.QPushButton(self.time_tab)
        self.reset_time_pushButton.setGeometry(QtCore.QRect(240, 100, 75, 23))
        self.reset_time_pushButton.setObjectName("reset_time_pushButton")
        self.subsample_tabWidget.addTab(self.time_tab, "")
        self.add_output_pushButton = QtWidgets.QPushButton(self.subset_frame)
        self.add_output_pushButton.setGeometry(QtCore.QRect(270, 210, 101, 31))
        self.add_output_pushButton.setObjectName("add_output_pushButton")
        self.output_frame = QtWidgets.QFrame(self.centralwidget)
        self.output_frame.setGeometry(QtCore.QRect(70, 440, 641, 261))
        self.output_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.output_frame.setObjectName("output_frame")
        self.run_pushButton = QtWidgets.QPushButton(self.output_frame)
        self.run_pushButton.setGeometry(QtCore.QRect(270, 210, 101, 41))
        self.run_pushButton.setObjectName("run_pushButton")
        self.remove_output_pushButton = QtWidgets.QPushButton(self.output_frame)
        self.remove_output_pushButton.setGeometry(QtCore.QRect(270, 10, 101, 31))
        self.remove_output_pushButton.setObjectName("remove_output_pushButton")
        self.output_listWidget = QtWidgets.QListWidget(self.output_frame)
        self.output_listWidget.setGeometry(QtCore.QRect(0, 50, 641, 151))
        self.output_listWidget.setObjectName("output_listWidget")
        self.info1_label = QtWidgets.QLabel(self.centralwidget)
        self.info1_label.setGeometry(QtCore.QRect(220, 800, 351, 20))
        self.info1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info1_label.setObjectName("info1_label")
        self.info3_label = QtWidgets.QLabel(self.centralwidget)
        self.info3_label.setGeometry(QtCore.QRect(220, 823, 351, 20))
        self.info3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info3_label.setObjectName("info3_label")
        self.info4_label = QtWidgets.QLabel(self.centralwidget)
        self.info4_label.setGeometry(QtCore.QRect(220, 836, 351, 20))
        self.info4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info4_label.setObjectName("info4_label")
        self.info2_label = QtWidgets.QLabel(self.centralwidget)
        self.info2_label.setGeometry(QtCore.QRect(220, 810, 351, 20))
        self.info2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info2_label.setObjectName("info2_label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(170, 740, 451, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.file_progress_label = QtWidgets.QLabel(self.centralwidget)
        self.file_progress_label.setGeometry(QtCore.QRect(170, 720, 421, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.file_progress_label.setFont(font)
        self.file_progress_label.setAlignment(QtCore.Qt.AlignCenter)
        self.file_progress_label.setObjectName("file_progress_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.subsample_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load_magellan_pushButton.setText(_translate("MainWindow", "Load Magellan Dataset"))
        self.remove_pushButton.setText(_translate("MainWindow", "Remove Dataset"))
        self.browse_pushButton.setText(_translate("MainWindow", "Browse"))
        self.auto_generate_pushButton.setText(_translate("MainWindow", "Auto Generate"))
        self.save_directory_label.setText(_translate("MainWindow", "Save Directory"))
        self.save_name_label.setText(_translate("MainWindow", "Save Name"))
        self.subsample_tabWidget.setTabText(self.subsample_tabWidget.indexOf(self.saving_tab), _translate("MainWindow", "Saving"))
        self.included_channels_label.setText(_translate("MainWindow", "Included Channels"))
        self.excluded_channels_label.setText(_translate("MainWindow", "Excluded Channels"))
        self.remove_channels_pushButton.setText(_translate("MainWindow", "Remove"))
        self.add_channels_pushButton.setText(_translate("MainWindow", "Add"))
        self.subsample_tabWidget.setTabText(self.subsample_tabWidget.indexOf(self.channel_tab), _translate("MainWindow", "Channels"))
        self.x_min_label.setText(_translate("MainWindow", "X Min"))
        self.x_max_label.setText(_translate("MainWindow", "X Max"))
        self.y_min_label.setText(_translate("MainWindow", "Y Min"))
        self.y_max_label.setText(_translate("MainWindow", "Y Max"))
        self.z_min_label.setText(_translate("MainWindow", "Z Min"))
        self.z_max_label.setText(_translate("MainWindow", "Z Max"))
        self.reset_space_pushButton.setText(_translate("MainWindow", "Reset All"))
        self.subsample_tabWidget.setTabText(self.subsample_tabWidget.indexOf(self.space_tab), _translate("MainWindow", "Space"))
        self.first_frame_label.setText(_translate("MainWindow", "First Frame"))
        self.label_3.setText(_translate("MainWindow", "Final Frame"))
        self.reset_time_pushButton.setText(_translate("MainWindow", "Reset"))
        self.subsample_tabWidget.setTabText(self.subsample_tabWidget.indexOf(self.time_tab), _translate("MainWindow", "Time"))
        self.add_output_pushButton.setText(_translate("MainWindow", "Add to Output"))
        self.run_pushButton.setText(_translate("MainWindow", "Run All"))
        self.remove_output_pushButton.setText(_translate("MainWindow", "Remove Output"))
        self.info1_label.setText(_translate("MainWindow", "PyMARIS Converter"))
        self.info3_label.setText(_translate("MainWindow", " Biological Imaging Development CoLab"))
        self.info4_label.setText(_translate("MainWindow", "University of California, San Fancisco 2019"))
        self.info2_label.setText(_translate("MainWindow", "Henry Pinkard and Kyle Marchuk"))
        self.file_progress_label.setText(_translate("MainWindow", "Progress:"))

